name: Rust-Binary-Build

on:
  push:
    branches: [ "main" ]
    tags:
    - v*
    - release/*
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release
    - name: Publish artifacts
      uses: actions/upload-artifact@master
      with:
        name: cimutil
        path: target/release/*.exe
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ 'build' ]
    if: startsWith(github.ref, 'refs/tags/release')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: cimutil
          path: build/
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
